---
abstract: "A Perl wrapper around OpenSSL's AES library"
author:
  - 'Tolga Tarhan'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Crypt-OpenSSL-AES
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.006002'
resources:
  repository: https://github.com/kmx/perl-Crypt-OpenSSL-AES
version: '0.03'
